# Generated by Django 3.1.4 on 2020-12-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercomment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='autor',
            new_name='author',
        ),
    ]
